Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
Traceback (most recent call last):
  File "generate_more_nolens.py", line 7, in <module>
    from data_generator_function import TiffImageDataGenerator
  File "/home/epfl/dforero/gravitational_lens_ml/src/data_generator_function.py", line 7, in <module>
    tf.debugging.set_log_device_placement(True)
AttributeError: module 'tensorflow._api.v1.debugging' has no attribute 'set_log_device_placement'
srun: error: node209: tasks 0-15: Exited with exit code 1
